
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // A placeholder lets `prisma generate` run before a local database is configured.
    // Migrations still require a real DATABASE_URL from `.env`.
    url: process.env.DATABASE_URL ?? "postgresql://postgres:postgres@localhost:5432/loop",
  },
});
