"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Report = { id: string; title: string; createdAt: string; contentJson: { facts?: { total: number; sentiment: Record<string, number>; topThemes: { name: string; count: number }[]; quotes: string[] }; narrative?: { summary?: string; actions?: string[] } } };
export default function ReportsPage() { const [reports, setReports] = useState<Report[]>([]); const [error, setError] = useState("");
  async function load() { const r = await fetch("/api/reports"); const d = await r.json(); if (r.ok) setReports(d); else setError(d.error || "Could not load reports"); }
  useEffect(() => { void load(); }, []);
  async function generate() { const r = await fetch("/api/reports", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({}) }); const d = await r.json(); if (!r.ok) setError(d.error); else { setError(""); await load(); } }
  return <main className="mx-auto min-h-screen max-w-5xl bg-slate-950 p-6 text-white"><Link href="/dashboard" className="text-blue-400 print:hidden">← Dashboard</Link><div className="my-6 flex justify-between print:hidden"><h1 className="text-3xl font-bold">Voice of Customer reports</h1><button onClick={generate} className="rounded bg-blue-600 px-4 py-2">Generate 7-day report</button></div><h1 className="my-6 hidden text-3xl font-bold print:block">Voice of Customer reports</h1>{error && <p role="alert">{error}</p>}{reports.map((report) => <article key={report.id} className="mb-4 rounded-xl border border-slate-800 bg-slate-900 p-5 print:border-slate-300 print:bg-white print:text-black"><div className="flex justify-between"><h2 className="font-semibold">{report.title}</h2><button onClick={() => window.print()} className="text-sm text-blue-400 print:hidden">Print / Save as PDF</button></div><p className="mt-2">{report.contentJson.narrative?.summary}</p><p className="mt-2 text-sm text-slate-400">{report.contentJson.facts?.total} items · {new Date(report.createdAt).toLocaleString()}</p><h3 className="mt-4 font-medium">Themes</h3><ul className="list-inside list-disc">{report.contentJson.facts?.topThemes.map((theme) => <li key={theme.name}>{theme.name}: {theme.count}</li>)}</ul><h3 className="mt-4 font-medium">Suggested actions</h3><ul className="list-inside list-disc">{report.contentJson.narrative?.actions?.map((action, i) => <li key={i}>{action}</li>)}</ul></article>)}</main>;
}
