"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Member = { id: string; name: string; email: string; role: string };
export default function MembersPage() { const [members, setMembers] = useState<Member[]>([]); const [error, setError] = useState("");
  async function load() { const r = await fetch("/api/members"); const data = await r.json(); if (r.ok) setMembers(data); else setError(data.error || "Admin access required"); }
  useEffect(() => { void load(); }, []);
  async function add(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const r = await fetch("/api/members", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await r.json(); if (!r.ok) setError(data.error); else { e.currentTarget.reset(); setError(""); await load(); } }
  async function role(id: string, value: string) { const r = await fetch("/api/members", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, role: value }) }); const data = await r.json(); if (!r.ok) setError(data.error); else { setError(""); await load(); } }
  return <main className="mx-auto min-h-screen max-w-4xl bg-slate-950 p-6 text-white"><Link href="/dashboard" className="text-blue-400">← Dashboard</Link><h1 className="my-6 text-3xl font-bold">Workspace members</h1>{error && <p role="alert" className="mb-4 rounded bg-slate-800 p-3">{error}</p>}<form onSubmit={add} className="grid gap-3 rounded-xl bg-slate-900 p-4 md:grid-cols-2"><input name="name" required placeholder="Name" className="rounded bg-slate-950 p-3" /><input name="email" type="email" required placeholder="Email" className="rounded bg-slate-950 p-3" /><input name="password" type="password" minLength={12} required placeholder="Temporary password (12+ characters)" className="rounded bg-slate-950 p-3" /><select name="role" className="rounded bg-slate-950 p-3"><option>ANALYST</option><option>VIEWER</option><option>ADMIN</option></select><button className="rounded bg-blue-600 p-3 md:col-span-2">Add member</button></form><div className="mt-6 space-y-3">{members.map((member) => <article key={member.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><div><p className="font-medium">{member.name}</p><p className="text-sm text-slate-400">{member.email}</p></div><select aria-label={`Role for ${member.name}`} value={member.role} onChange={(e) => role(member.id, e.target.value)} className="rounded bg-slate-950 p-2"><option>ADMIN</option><option>ANALYST</option><option>VIEWER</option></select></article>)}</div></main>;
}
