"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
type Item = { id: string; content: string; channel: string; status: string; sentiment: string | null; createdAt: string; themes: { theme: { name: string } }[] };
type ThemeOption = { id: string; name: string };
export default function InboxPage() {
  const [items, setItems] = useState<Item[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [filterChannel, setFilterChannel] = useState(""); const [sentiment, setSentiment] = useState(""); const [theme, setTheme] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [themes, setThemes] = useState<ThemeOption[]>([]); const [error, setError] = useState(""); const [content, setContent] = useState(""); const [channel, setChannel] = useState("Support ticket");
  const load = useCallback(async () => { const params = new URLSearchParams({ page: "1", pageSize: "50" }); for (const [key, value] of Object.entries({ q: query, status, channel: filterChannel, sentiment, theme, from, to })) if (value) params.set(key, value); const r = await fetch(`/api/feedback?${params}`); const data = await r.json(); if (r.ok) setItems(data.items); else setError(data.error || "Could not load inbox"); }, [query, status, filterChannel, sentiment, theme, from, to]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void fetch("/api/themes").then((r) => r.json()).then((data) => setThemes(Array.isArray(data) ? data : [])); }, []);
  async function add(e: React.FormEvent) { e.preventDefault(); const r = await fetch("/api/feedback", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ content, channel }) }); const data = await r.json(); if (!r.ok) { setError(data.error); return; } setContent(""); await load(); }
  async function update(id: string, next: string) { await fetch(`/api/feedback/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: next }) }); await load(); }
  async function reclassify(id: string) { const r = await fetch(`/api/feedback/${id}`, { method: "POST" }); const d = await r.json(); if (!r.ok) setError(d.error); else { setError("Reclassified feedback."); await load(); } }
  async function simulate() { const r = await fetch("/api/feedback/simulate", { method: "POST" }); const d = await r.json(); setError(r.ok ? `Imported ${d.imported} simulated items.` : d.error); await load(); }
  async function upload(e: React.ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; const form = new FormData(); form.set("file", file); const r = await fetch("/api/feedback/import", { method: "POST", body: form }); const data = await r.json(); setError(r.ok ? `Imported ${data.imported}; failed ${data.failed}.` : data.error); await load(); }
  return <main className="mx-auto min-h-screen max-w-6xl bg-slate-950 p-6 text-white"><Link href="/dashboard" className="text-blue-400">← Dashboard</Link><h1 className="my-5 text-3xl font-bold">Feedback inbox</h1>{error && <p role="status" className="mb-4 rounded bg-slate-800 p-3">{error}</p>}
  <form onSubmit={add} className="mb-6 grid gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4 md:grid-cols-4"><input className="rounded bg-slate-950 p-3 md:col-span-2" placeholder="Customer feedback" value={content} onChange={(e) => setContent(e.target.value)} required /><input className="rounded bg-slate-950 p-3" value={channel} onChange={(e) => setChannel(e.target.value)} aria-label="Channel" required /><button className="rounded bg-blue-600 p-3">Add feedback</button><label className="text-sm text-slate-300">Import CSV<input type="file" accept=".csv,text/csv" onChange={upload} className="ml-2" /></label><button type="button" onClick={simulate} className="rounded border border-slate-700 p-2">Simulate channel import</button></form>
  <div className="mb-4 flex flex-wrap gap-3"><input className="rounded bg-slate-900 p-3" placeholder="Search content" value={query} onChange={(e) => setQuery(e.target.value)} /><select className="rounded bg-slate-900 p-3" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option>NEW</option><option>REVIEWED</option><option>ACTIONED</option></select><select className="rounded bg-slate-900 p-3" value={filterChannel} onChange={(e) => setFilterChannel(e.target.value)}><option value="">All channels</option>{["Support ticket", "App store review", "NPS survey", "Sales call note", "Community post"].map((v) => <option key={v}>{v}</option>)}</select><select className="rounded bg-slate-900 p-3" value={sentiment} onChange={(e) => setSentiment(e.target.value)}><option value="">All sentiments</option><option>POS</option><option>NEU</option><option>NEG</option></select><select className="rounded bg-slate-900 p-3" value={theme} onChange={(e) => setTheme(e.target.value)}><option value="">All themes</option>{themes.map((v) => <option value={v.id} key={v.id}>{v.name}</option>)}</select><label className="text-xs text-slate-400">From<input aria-label="From date" type="date" className="ml-1 rounded bg-slate-900 p-2" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label className="text-xs text-slate-400">To<input aria-label="To date" type="date" className="ml-1 rounded bg-slate-900 p-2" value={to} onChange={(e) => setTo(e.target.value)} /></label></div>
  <div className="space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-wrap justify-between gap-3"><p className="max-w-3xl">{item.content}</p><div className="flex gap-2"><select aria-label="Feedback status" className="h-10 rounded bg-slate-950 p-2" value={item.status} onChange={(e) => update(item.id, e.target.value)}><option>NEW</option><option>REVIEWED</option><option>ACTIONED</option></select><button onClick={() => reclassify(item.id)} className="rounded border border-slate-700 px-3 text-sm">Reclassify</button></div></div><p className="mt-3 text-xs text-slate-400">{item.channel} · {item.sentiment || "Unclassified"} · {new Date(item.createdAt).toLocaleDateString()} · {item.themes.map((t) => t.theme.name).join(", ")}</p></article>)}</div>{!items.length && <p className="p-8 text-center text-slate-400">No matching feedback.</p>}</main>;
}
